FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install --silent
COPY . ./
RUN npm run build

FROM node:13.12.0-alpine
WORKDIR /usr/src/app
COPY --from=build /app/build /usr/src/app/build
RUN npm install -g serve
ENTRYPOINT [ "serve", "-s", "build", "-l", "3000" ]