version: '3'

services:
  backend:
    container_name: tasker_backend_prod
    build: 
        context: ./app
        dockerfile: Dockerfile.prod
    image: registry.gitlab.com/markhoward/container-registry/tasker_app_backend
    expose:
      - 8080
    depends_on:
      - db

  frontend:
    container_name: tasker_frontend_prod
    build: 
        context: ./frontend
        dockerfile: Dockerfile.prod
    image: registry.gitlab.com/markhoward/container-registry/tasker_app_frontend
    expose:
      - 3000

  db:
    container_name: tasker_db_prod
    build: ./database
    image: registry.gitlab.com/markhoward/container-registry/tasker_app_db
    volumes:
      - mysql_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-squirrel
      - MYSQL_DATABASE=database-name
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  nginx:
    container_name: tasker_nginx_prod
    build: ./nginx
    image: registry.gitlab.com/markhoward/container-registry/tasker_app_nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
volumes:
  mysql_data_prod: