version: '3'

services:
  backend:
    container_name: spring_backend
    command: ./gradlew bootRun
    build: ./app
    expose:
      - 8080
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    container_name: react_frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    container_name: mysql_db
    build: ./database
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-squirrel
      - MYSQL_DATABASE=database-name
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  node_modules: